name: Daily Automated Bot Run

# runs the bot at a set time everyday

on:
  schedule:
    - cron: '0 8 * * *'  # 12PM PST/1AM PDT = 8AM UTC
  workflow_dispatch:  # allows manual triggering

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore schedule cache
        uses: actions/cache@v4
        with:
          path: home_games_schedule.json
          key: schedule-cache

      - name: Run Dodgers win check
        run: python bot.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_ROLE_ID: ${{ secrets.DISCORD_ROLE_ID }}

      - name: Save schedule cache
        uses: actions/cache@v4
        with:
          path: home_games_schedule.json
          key: schedule-cache

      - name: Upload schedule file as artifact (for debugging)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: schedule-data
          path: home_games_schedule.json 